// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/labstack/echo/v4"
	"time"
)

// ActorURI defines model for ActorURI.
type ActorURI string

// ConsentRecord defines model for ConsentRecord.
type ConsentRecord struct {
	ConsentProof       DocumentReference    `json:"consentProof"`
	DataClass          []DataClassification `json:"dataClass"`
	Period             Period               `json:"period"`
	PreviousRecordHash *string              `json:"previousRecordHash,omitempty"`
}

// CreateConsentRequest defines model for CreateConsentRequest.
type CreateConsentRequest struct {
	Actor     ActorURI        `json:"actor"`
	Custodian CustodianURI    `json:"custodian"`
	Performer *IdentifierURI  `json:"performer,omitempty"`
	Records   []ConsentRecord `json:"records"`
	Subject   SubjectURI      `json:"subject"`
}

// CustodianURI defines model for CustodianURI.
type CustodianURI string

// DataClassification defines model for DataClassification.
type DataClassification string

// DocumentReference defines model for DocumentReference.
type DocumentReference struct {
	ID          string  `json:"ID"`
	URL         *string `json:"URL,omitempty"`
	ContentType *string `json:"contentType,omitempty"`
	Hash        *string `json:"hash,omitempty"`
	Title       string  `json:"title"`
}

// IdentifierURI defines model for IdentifierURI.
type IdentifierURI string

// JobCreatedResponse defines model for JobCreatedResponse.
type JobCreatedResponse struct {
	JobId      *string `json:"jobId,omitempty"`
	ResultCode string  `json:"resultCode"`
}

// Period defines model for Period.
type Period struct {
	End   *time.Time `json:"end,omitempty"`
	Start time.Time  `json:"start"`
}

// SubjectURI defines model for SubjectURI.
type SubjectURI string

// createOrUpdateConsentJSONBody defines parameters for CreateOrUpdateConsent.
type createOrUpdateConsentJSONBody CreateConsentRequest

// CreateOrUpdateConsentRequestBody defines body for CreateOrUpdateConsent for application/json ContentType.
type CreateOrUpdateConsentJSONRequestBody createOrUpdateConsentJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create or update a new consent.// (POST /api/consent)
	CreateOrUpdateConsent(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateOrUpdateConsent converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrUpdateConsent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateOrUpdateConsent(ctx)
	return err
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router runtime.EchoRouter, si ServerInterface) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST("/api/consent", wrapper.CreateOrUpdateConsent)

}

